In [1]:
import tmdbsimple as tmdb
tmdb.API_KEY = '860152e6c4f46e7ea6700b28d6678ae3'
import pandas as pd

In [2]:
from urllib.error import HTTPError

In [3]:
movie = tmdb.Movies(603)
response = movie.info()
movie.title

'The Matrix'

In [4]:
keywords_animation=[]

In [5]:
for i in range(1,8):
    keywords_animation += (tmdb.Search().keyword(query='animation', page=i)['results'][:])

In [7]:
kw_ids_2d = [kw['id'] for kw in keywords_animation if any(w in kw['name'] for w in ['traditional', '2d', 'cel', 'hand drawn', 'ink paint'])]

In [8]:
kw_ids_2d

[243752, 367675, 366485, 287990, 234662, 332159]

In [9]:
movies2d = tmdb.Discover().movie(with_genres='16', with_keywords='243752|367675|366485|287990|234662')

In [11]:
import requests

In [12]:
mdblist_api_key = 'jdgs0h5ib5jdbf6hc8mphmwa8'

In [13]:
response = requests.get('https://api.mdblist.com/lists/user?apikey='+mdblist_api_key)

In [15]:
list_ids = [[mdblist['id'], mdblist['name']] for mdblist in response.json()]

In [16]:
list_ids[1][0]

158471

In [17]:
movies_3d_response = requests.get(f'https://api.mdblist.com/lists/{list_ids[0][0]}/items?apikey={mdblist_api_key}')

In [18]:
movies_3d = movies_3d_response.json()['movies']

In [19]:
movies_3d_response = requests.get(f'https://api.mdblist.com/lists/{list_ids[0][0]}/items?apikey={mdblist_api_key}&offset=1000')

In [20]:
movies_3d += movies_3d_response.json()['movies']

In [21]:
movies_3d_response = requests.get(f'https://api.mdblist.com/lists/{list_ids[0][0]}/items?apikey={mdblist_api_key}&offset=2000')

In [22]:
movies_3d += movies_3d_response.json()['movies']

In [24]:
movies_2d_response = requests.get(f'https://api.mdblist.com/lists/{list_ids[1][0]}/items?apikey={mdblist_api_key}')

In [25]:
movies_2d = movies_2d_response.json()['movies']

In [26]:
movies_2d_response = requests.get(f'https://api.mdblist.com/lists/{list_ids[1][0]}/items?apikey={mdblist_api_key}&offset=1000')

In [27]:
movies_2d += movies_2d_response.json()['movies']

In [28]:
movies_2d_response = requests.get(f'https://api.mdblist.com/lists/{list_ids[1][0]}/items?apikey={mdblist_api_key}&offset=2000')

In [29]:
movies_2d += movies_2d_response.json()['movies']

In [30]:
movies_2d_response = requests.get(f'https://api.mdblist.com/lists/{list_ids[1][0]}/items?apikey={mdblist_api_key}&offset=3000')

In [31]:
movies_2d += movies_2d_response.json()['movies']

In [34]:
movies_3d_df = pd.DataFrame(movies_3d)

In [35]:
movies_3d_df

,id,ids,rank,adult,title,status,country,imdb_id,runtime,tvdb_id,language,mediatype,release_date,release_year,spoken_language
0,569094,"{'imdb': 'tt9362722', 'tmdb': 569094, 'tvdb': ...",1,0,Spider-Man: Across the Spider-Verse,Released,us,tt9362722,140.0,132814.0,en,movie,2023-05-31,2023.0,en
1,324857,"{'imdb': 'tt4633694', 'tmdb': 324857, 'tvdb': ...",2,0,Spider-Man: Into the Spider-Verse,Released,us,tt4633694,117.0,33.0,en,movie,2018-12-06,2018.0,en
2,1184918,"{'imdb': 'tt29623480', 'tmdb': 1184918, 'tvdb'...",3,0,The Wild Robot,released,us,tt29623480,102.0,353646.0,en,movie,2024-09-12,2024.0,en
3,823219,"{'imdb': 'tt4772188', 'tmdb': 823219, 'tvdb': ...",4,0,Flow,released,lv,tt4772188,85.0,356056.0,lv,movie,2024-08-29,2024.0,xx
4,2062,"{'imdb': 'tt0382932', 'tmdb': 2062, 'tvdb': 53...",5,0,Ratatouille,Released,us,tt0382932,111.0,534.0,en,movie,2007-06-28,2007.0,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2274,729501,"{'imdb': 'tr571827', 'tmdb': 729501, 'tvdb': N...",2275,0,ROACH™,released,ca,tr571827,31.0,NaN,en,movie,2022-12-10,2022.0,None
2275,438247,"{'imdb': 'tr284432', 'tmdb': 438247, 'tvdb': N...",2276,0,Doomed: A Biological Cartoon!,released,es,tr284432,10.0,NaN,en,movie,2011-01-30,2011.0,en
2276,743540,"{'imdb': 'tt13334482', 'tmdb': 743540, 'tvdb':...",2277,0,Distracted Blueberry,released,ca,tt13334482,273.0,NaN,fr,movie,2019-10-24,2019.0,fr
2277,737029,"{'imdb': 'tt3226448', 'tmdb': 737029, 'tvdb': ...",2278,0,Animusic 3,in production,us,tt3226448,90.0,NaN,en,movie,None,NaN,None
2278,719147,"{'imdb': 'tr561533', 'tmdb': 719147, 'tvdb': N...",2279,0,Outremer,released,fr,tr561533,3.0,NaN,en,movie,2017-09-15,2017.0,None

In [36]:
movies_2d_df = pd.DataFrame(movies_2d)

In [37]:
movies_3d_df = pd.merge(movies_3d_df, pd.json_normalize(movies_3d_df['ids']), left_index=True, right_index=True).drop(columns='ids')

In [38]:
movies_2d_df = pd.merge(movies_2d_df, pd.json_normalize(movies_2d_df['ids']), left_index=True, right_index=True).drop(columns='ids')

In [39]:
movies_2d_df[movies_2d_df.tmdb == 1266996]

,id,rank,adult,title,status,country,imdb_id,runtime,tvdb_id,language,mediatype,release_date,release_year,spoken_language,imdb,tmdb,tvdb,mdblist
1905,1266996,1906,0,The Dark Knight's First Night,Released,us,tt3366668,2.0,NaN,en,movie,1992-03-16,1992.0,xx,tt3366668,1266996,NaN,3e6va

In [40]:
movies_3d_df.to_csv('3D_Movies.csv')

In [41]:
movies_2d_df.to_csv('2D_Movies.csv')

In [42]:
movies_3d_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2279 entries, 0 to 2278
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2279 non-null   int64
 1   rank             2279 non-null   int64
 2   adult            2279 non-null   int64
 3   title            2279 non-null   object
 4   status           2279 non-null   object
 5   country          2246 non-null   object
 6   imdb_id          2270 non-null   object
 7   runtime          2269 non-null   float64
 8   tvdb_id          1240 non-null   float64
 9   language         2279 non-null   object
 10  mediatype        2279 non-null   object
 11  release_date     2226 non-null   object
 12  release_year     2233 non-null   float64
 13  spoken_language  1878 non-null   object
 14  imdb             2270 non-null   object
 15  tmdb             2279 non-null   int64
 16  tvdb             1240 non-null   float64
 17  mdblist          2279 non-null   object
dtypes: float64(4), int64(4), object(10)
memory usage: 320.6+ KB

In [2]:
tmdb_2d = []

In [3]:
for i, row in movies_2d_df.iterrows():
    try:
        tmdb_2d.append(tmdb.Movies(row['tmdb']).info())
    except:
        continue

NameError: name 'movies_2d_df' is not defined

In [49]:
tmdb_3d = []

In [50]:
for i, row in movies_3d_df.iterrows():
    try:
        tmdb_3d.append(tmdb.Movies(row['tmdb']).info())
    except:
        continue

In [181]:
tmdb_movies_2d = pd.DataFrame(tmdb_2d)

In [182]:
tmdb_movies_2d = tmdb_movies_2d[['title', 'id', 'genres', 'overview', 'release_date', 'runtime', 'budget', 'revenue', 'origin_country', 'original_language', 'spoken_languages', 'production_companies', 'production_countries', 'vote_average', 'vote_count', 'popularity']]

In [183]:
tmdb_movies_2d['genres'][0]

[{'id': 16, 'name': 'Animation'},
 {'id': 10751, 'name': 'Family'},
 {'id': 14, 'name': 'Fantasy'}]

In [184]:
str([g['name'] for g in tmdb_movies_2d['genres'][0]])[1:-1].replace('\'', '').replace(',', ';')

'Animation; Family; Fantasy'

In [185]:
for i, row in tmdb_movies_2d.iterrows():
    tmdb_movies_2d.loc[i, 'genres_list'] = str([g['name'] for g in row['genres']])[1:-1].replace('\'', '')

In [186]:
tmdb_movies_2d.head()

,title,id,genres,overview,release_date,runtime,budget,revenue,origin_country,original_language,spoken_languages,production_companies,production_countries,vote_average,vote_count,popularity,genres_list
0,Spirited Away,129,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...","A young girl, Chihiro, becomes trapped in a st...",2001-07-20,125,19000000,274925095,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 10342, 'logo_path': '/uFuxPEZRUcBTEiYI...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.500,18194,35.0613,"Animation, Family, Fantasy"
1,Attack on Titan: THE LAST ATTACK,1333100,"[{'id': 16, 'name': 'Animation'}, {'id': 28, '...",A colossal-sized omnibus film bringing togethe...,2024-03-20,145,0,21525687,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 21444, 'logo_path': '/wSejGn3lAZdQ5muB...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.736,184,6.8777,"Animation, Action, Adventure, Drama"
2,Grave of the Fireflies,12477,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...","In the final months of World War II, 14-year-o...",1988-04-16,89,3700000,842132,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 10342, 'logo_path': '/uFuxPEZRUcBTEiYI...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.400,6473,0.0148,"Animation, Drama, War"
3,Violet Evergarden: The Movie,533514,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...",As the world moves on from the war and technol...,2020-09-18,140,0,20339624,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 5438, 'logo_path': '/leZ8GPCL0GneHHayP...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.287,501,7.8410,"Animation, Drama, Fantasy, Romance"
4,Look Back,1244492,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...","Popular, outgoing Fujino is celebrated by her ...",2024-06-28,58,0,12648664,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 136998, 'logo_path': '/4Gw6jh3aUoJArME...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.000,525,9.6644,"Animation, Drama"

In [187]:
tmdb_movies_2d['production_companies'][0]

[{'id': 10342,
  'logo_path': '/uFuxPEZRUcBTEiYIxjHJq62Vr77.png',
  'name': 'Studio Ghibli',
  'origin_country': 'JP'},
 {'id': 1779,
  'logo_path': '/41nGzTdCnORYZIZzaGZtfsBwQCl.png',
  'name': 'Tokuma Shoten',
  'origin_country': 'JP'},
 {'id': 6755,
  'logo_path': '/bWiM2iY82B32NGmPCOFatgfekIR.png',
  'name': 'Nippon Television Network Corporation',
  'origin_country': 'JP'},
 {'id': 11847,
  'logo_path': '/rZP0I1p3hZNUMNFPHUSal6rWThQ.png',
  'name': 'Mitsubishi',
  'origin_country': 'JP'},
 {'id': 1778,
  'logo_path': '/b5rT6VbYza3LyfltCmz1OcqzWJM.png',
  'name': 'dentsu',
  'origin_country': 'JP'},
 {'id': 1780,
  'logo_path': '/4Qzhr7FxVtaMwmsh7118G3yvOhO.png',
  'name': 'TFC',
  'origin_country': 'JP'}]

In [188]:
for i, row in tmdb_movies_2d.iterrows():
    tmdb_movies_2d.loc[i, 'production_companies_list'] = str([g['name'] for g in row['production_companies']])[1:-1]

In [189]:
tmdb_movies_2d.head()

,title,id,genres,overview,release_date,runtime,budget,revenue,origin_country,original_language,spoken_languages,production_companies,production_countries,vote_average,vote_count,popularity,genres_list,production_companies_list
0,Spirited Away,129,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...","A young girl, Chihiro, becomes trapped in a st...",2001-07-20,125,19000000,274925095,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 10342, 'logo_path': '/uFuxPEZRUcBTEiYI...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.500,18194,35.0613,"Animation, Family, Fantasy","'Studio Ghibli', 'Tokuma Shoten', 'Nippon Tele..."
1,Attack on Titan: THE LAST ATTACK,1333100,"[{'id': 16, 'name': 'Animation'}, {'id': 28, '...",A colossal-sized omnibus film bringing togethe...,2024-03-20,145,0,21525687,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 21444, 'logo_path': '/wSejGn3lAZdQ5muB...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.736,184,6.8777,"Animation, Action, Adventure, Drama","'MAPPA', 'Pony Canyon'"
2,Grave of the Fireflies,12477,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...","In the final months of World War II, 14-year-o...",1988-04-16,89,3700000,842132,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 10342, 'logo_path': '/uFuxPEZRUcBTEiYI...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.400,6473,0.0148,"Animation, Drama, War",'Studio Ghibli'
3,Violet Evergarden: The Movie,533514,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...",As the world moves on from the war and technol...,2020-09-18,140,0,20339624,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 5438, 'logo_path': '/leZ8GPCL0GneHHayP...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.287,501,7.8410,"Animation, Drama, Fantasy, Romance","'Kyoto Animation', 'ABC Animation', 'Pony Cany..."
4,Look Back,1244492,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...","Popular, outgoing Fujino is celebrated by her ...",2024-06-28,58,0,12648664,[JP],ja,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...","[{'id': 136998, 'logo_path': '/4Gw6jh3aUoJArME...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",8.000,525,9.6644,"Animation, Drama","'Studio Durian', 'avex pictures', 'Shueisha'"

In [190]:
tmdb_movies_2d['production_countries'][0]

[{'iso_3166_1': 'JP', 'name': 'Japan'}]

In [191]:
for i, row in tmdb_movies_2d.iterrows():
    tmdb_movies_2d.loc[i, 'production_countries_list'] = str([g['iso_3166_1'] for g in row['production_countries']])[1:-1].replace('\'', '')

In [192]:
tmdb_movies_2d.drop(columns=['genres', 'spoken_languages', 'production_companies', 'production_countries'], inplace=True)

In [176]:
tmdb_movies_3d = pd.DataFrame(tmdb_3d)

In [177]:
tmdb_movies_3d = tmdb_movies_3d[['title', 'id', 'genres', 'overview', 'release_date', 'runtime', 'budget', 'revenue', 'origin_country', 'original_language', 'spoken_languages', 'production_companies', 'production_countries', 'vote_average', 'vote_count', 'popularity']]

In [178]:
tmdb_movies_3d

,title,id,genres,overview,release_date,runtime,budget,revenue,origin_country,original_language,spoken_languages,production_companies,production_countries,vote_average,vote_count,popularity
0,Spider-Man: Across the Spider-Verse,569094,"[{'id': 16, 'name': 'Animation'}, {'id': 28, '...","After reuniting with Gwen Stacy, Brooklyn’s fu...",2023-05-31,140,100000000,690897910,[US],en,"[{'english_name': 'English', 'iso_639_1': 'en'...","[{'id': 5, 'logo_path': '/71BqEFAF4V3qjjMPCpLu...","[{'iso_3166_1': 'US', 'name': 'United States o...",8.332,8484,28.9949
1,Spider-Man: Into the Spider-Verse,324857,"[{'id': 16, 'name': 'Animation'}, {'id': 28, '...",Struggling to find his place in the world whil...,2018-12-06,117,90000000,394884133,[US],en,"[{'english_name': 'English', 'iso_639_1': 'en'...","[{'id': 5, 'logo_path': '/71BqEFAF4V3qjjMPCpLu...","[{'iso_3166_1': 'US', 'name': 'United States o...",8.393,17105,23.6672
2,The Wild Robot,1184918,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...","After a shipwreck, an intelligent robot called...",2024-09-12,102,78000000,331982078,[US],en,"[{'english_name': 'English', 'iso_639_1': 'en'...","[{'id': 521, 'logo_path': '/3BPX5VGBov8SDqTV7w...","[{'iso_3166_1': 'US', 'name': 'United States o...",8.305,5949,28.6254
3,Flow,823219,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...","A solitary cat, displaced by a great flood, fi...",2024-08-29,85,3700000,17660107,[LV],lv,"[{'english_name': 'No Language', 'iso_639_1': ...","[{'id': 153335, 'logo_path': '/bEsO7l12cRGAY25...","[{'iso_3166_1': 'LV', 'name': 'Latvia'}, {'iso...",8.084,2760,19.2123
4,Ratatouille,2062,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Remy, a rat, possesses a palate far more refin...",2007-06-28,111,150000000,623726000,[US],en,"[{'english_name': 'English', 'iso_639_1': 'en'...","[{'id': 3, 'logo_path': '/1TjvGVDMYsj6JBxOAkUH...","[{'iso_3166_1': 'US', 'name': 'United States o...",7.838,18370,13.9543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269,ROACH™,729501,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",A young pilot narrowly escapes the destruction...,2022-12-10,31,2000,0,"[CA, US]",en,"[{'english_name': 'English', 'iso_639_1': 'en'...","[{'id': 123937, 'logo_path': None, 'name': 'sc...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]",0.000,0,0.5473
2270,Doomed: A Biological Cartoon!,438247,"[{'id': 16, 'name': 'Animation'}]",A fake documentary about the life and habits o...,2011-01-30,10,0,0,[US],en,[],"[{'id': 158198, 'logo_path': None, 'name': 'El...","[{'iso_3166_1': 'ES', 'name': 'Spain'}]",0.000,0,0.0505
2271,Distracted Blueberry,743540,"[{'id': 16, 'name': 'Animation'}]",Masculine tropes are undone to form a relation...,2019-10-24,273,0,0,[CA],fr,"[{'english_name': 'French', 'iso_639_1': 'fr',...",[],"[{'iso_3166_1': 'CA', 'name': 'Canada'}]",0.000,0,0.0256
2272,Animusic 3,737029,"[{'id': 16, 'name': 'Animation'}, {'id': 10402...",Animusic is a great electronic music experienc...,,0,223123,0,[US],en,[],"[{'id': 161095, 'logo_path': '/A4j2XOW7wG0Ip2y...","[{'iso_3166_1': 'US', 'name': 'United States o...",0.000,0,0.0409
2273,Outremer,719147,"[{'id': 16, 'name': 'Animation'}, {'id': 14, '...",It's a story about a young boy who is afraid o...,2017-09-15,3,0,0,[US],en,"[{'english_name': 'No Language', 'iso_639_1': ...","[{'id': 71552, 'logo_path': '/hmFPR24kEVCPi6A4...","[{'iso_3166_1': 'FR', 'name': 'France'}]",0.000,0,0.1208

In [179]:
for i, row in tmdb_movies_3d.iterrows():
    tmdb_movies_3d.loc[i, 'genres_list'] = str([g['name'] for g in row['genres']])[1:-1].replace('\'', '')
for i, row in tmdb_movies_3d.iterrows():
    tmdb_movies_3d.loc[i, 'production_companies_list'] = str([g['name'] for g in row['production_companies']])[1:-1]
for i, row in tmdb_movies_3d.iterrows():
    tmdb_movies_3d.loc[i, 'production_countries_list'] = str([g['iso_3166_1'] for g in row['production_countries']])[1:-1].replace('\'', '')
tmdb_movies_3d.drop(columns=['genres', 'spoken_languages', 'production_companies', 'production_countries'], inplace=True)

In [180]:
tmdb_movies_3d

,title,id,overview,release_date,runtime,budget,revenue,origin_country,original_language,vote_average,vote_count,popularity,genres_list,production_companies_list,production_countries_list
0,Spider-Man: Across the Spider-Verse,569094,"After reuniting with Gwen Stacy, Brooklyn’s fu...",2023-05-31,140,100000000,690897910,[US],en,8.332,8484,28.9949,"Animation, Action, Adventure, Science Fiction","'Columbia Pictures', 'Sony Pictures Animation'...",US
1,Spider-Man: Into the Spider-Verse,324857,Struggling to find his place in the world whil...,2018-12-06,117,90000000,394884133,[US],en,8.393,17105,23.6672,"Animation, Action, Adventure, Science Fiction","'Columbia Pictures', 'Lord Miller', 'Pascal Pi...",US
2,The Wild Robot,1184918,"After a shipwreck, an intelligent robot called...",2024-09-12,102,78000000,331982078,[US],en,8.305,5949,28.6254,"Family, Animation, Science Fiction, Adventure",'DreamWorks Animation',US
3,Flow,823219,"A solitary cat, displaced by a great flood, fi...",2024-08-29,85,3700000,17660107,[LV],lv,8.084,2760,19.2123,"Animation, Adventure, Fantasy, Family","'Dream Well Studio', 'Sacrebleu Productions', ...","LV, BE, FR"
4,Ratatouille,2062,"Remy, a rat, possesses a palate far more refin...",2007-06-28,111,150000000,623726000,[US],en,7.838,18370,13.9543,"Animation, Comedy, Family, Fantasy",'Pixar',US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269,ROACH™,729501,A young pilot narrowly escapes the destruction...,2022-12-10,31,2000,0,"[CA, US]",en,0.000,0,0.5473,"Science Fiction, Animation",'schnüdlbug',CA
2270,Doomed: A Biological Cartoon!,438247,A fake documentary about the life and habits o...,2011-01-30,10,0,0,[US],en,0.000,0,0.0505,Animation,'El Señor Studio',ES
2271,Distracted Blueberry,743540,Masculine tropes are undone to form a relation...,2019-10-24,273,0,0,[CA],fr,0.000,0,0.0256,Animation,,CA
2272,Animusic 3,737029,Animusic is a great electronic music experienc...,,0,223123,0,[US],en,0.000,0,0.0409,"Animation, Music, Family","'Animusic, LLC'",US
2273,Outremer,719147,It's a story about a young boy who is afraid o...,2017-09-15,3,0,0,[US],en,0.000,0,0.1208,"Animation, Fantasy, Drama, Family","'Gobelins', ""L'école de l'image""",FR

In [193]:
tmdb_movies_2d

,title,id,overview,release_date,runtime,budget,revenue,origin_country,original_language,vote_average,vote_count,popularity,genres_list,production_companies_list,production_countries_list
0,Spirited Away,129,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,125,19000000,274925095,[JP],ja,8.500,18194,35.0613,"Animation, Family, Fantasy","'Studio Ghibli', 'Tokuma Shoten', 'Nippon Tele...",JP
1,Attack on Titan: THE LAST ATTACK,1333100,A colossal-sized omnibus film bringing togethe...,2024-03-20,145,0,21525687,[JP],ja,8.736,184,6.8777,"Animation, Action, Adventure, Drama","'MAPPA', 'Pony Canyon'",JP
2,Grave of the Fireflies,12477,"In the final months of World War II, 14-year-o...",1988-04-16,89,3700000,842132,[JP],ja,8.400,6473,0.0148,"Animation, Drama, War",'Studio Ghibli',JP
3,Violet Evergarden: The Movie,533514,As the world moves on from the war and technol...,2020-09-18,140,0,20339624,[JP],ja,8.287,501,7.8410,"Animation, Drama, Fantasy, Romance","'Kyoto Animation', 'ABC Animation', 'Pony Cany...",JP
4,Look Back,1244492,"Popular, outgoing Fujino is celebrated by her ...",2024-06-28,58,0,12648664,[JP],ja,8.000,525,9.6644,"Animation, Drama","'Studio Durian', 'avex pictures', 'Shueisha'",JP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3085,Me...Jane,548663,Patrick McDonnell tells the story of the young...,2015-01-10,9,0,0,[US],en,0.000,0,0.1938,"Family, Animation","'Weston Woods Studios', 'Scholastic Productions'",US
3086,Horizon Blue,745313,"The latest from Hiroshi Harada, an adaptation ...",2020-04-25,112,0,0,[JP],ja,0.000,0,0.2621,"Drama, Animation",'Kiryûkan',JP
3087,The Missing Pig,720636,A mysterious pig disappearance brings chaos to...,2018-09-28,4,0,0,[GB],en,0.000,0,0.1125,"Comedy, Animation",,GB
3088,Slocum at Sea with Himself,736019,I was a self-taught sailor of marginal skills ...,2015-09-10,123,0,0,[US],en,0.000,0,0.0363,Animation,,
3089,Nova,744009,A young astronaut works in solitude on a space...,2020-07-30,5,0,0,[US],en,0.000,0,0.0454,"Animation, Drama, Science Fiction, Horror",,

In [196]:
crew = tmdb.Movies(129).credits()['crew']

In [200]:
[d['name'] for d in crew if d['job'] == 'Director'][0]

'Hayao Miyazaki'

In [203]:
for i, row in tmdb_movies_2d.iterrows():
    crew = tmdb.Movies(row['id']).credits()['crew']
    tmdb_movies_2d.loc[i, 'director'] = str([d['name'] for d in crew if d['job'] == 'Director'])[1:-1].replace('\'', '')

In [205]:
for i, row in tmdb_movies_3d.iterrows():
    crew = tmdb.Movies(row['id']).credits()['crew']
    tmdb_movies_3d.loc[i, 'director'] = str([d['name'] for d in crew if d['job'] == 'Director'])[1:-1].replace('\'', '')

In [206]:
tmdb_movies_3d

,title,id,overview,release_date,runtime,budget,revenue,origin_country,original_language,vote_average,vote_count,popularity,genres_list,production_companies_list,production_countries_list,director
0,Spider-Man: Across the Spider-Verse,569094,"After reuniting with Gwen Stacy, Brooklyn’s fu...",2023-05-31,140,100000000,690897910,[US],en,8.332,8484,28.9949,"Animation, Action, Adventure, Science Fiction","'Columbia Pictures', 'Sony Pictures Animation'...",US,"Kemp Powers, Justin K. Thompson, Joaquim Dos S..."
1,Spider-Man: Into the Spider-Verse,324857,Struggling to find his place in the world whil...,2018-12-06,117,90000000,394884133,[US],en,8.393,17105,23.6672,"Animation, Action, Adventure, Science Fiction","'Columbia Pictures', 'Lord Miller', 'Pascal Pi...",US,"Bob Persichetti, Peter Ramsey, Rodney Rothman"
2,The Wild Robot,1184918,"After a shipwreck, an intelligent robot called...",2024-09-12,102,78000000,331982078,[US],en,8.305,5949,28.6254,"Family, Animation, Science Fiction, Adventure",'DreamWorks Animation',US,Chris Sanders
3,Flow,823219,"A solitary cat, displaced by a great flood, fi...",2024-08-29,85,3700000,17660107,[LV],lv,8.084,2760,19.2123,"Animation, Adventure, Fantasy, Family","'Dream Well Studio', 'Sacrebleu Productions', ...","LV, BE, FR",Gints Zilbalodis
4,Ratatouille,2062,"Remy, a rat, possesses a palate far more refin...",2007-06-28,111,150000000,623726000,[US],en,7.838,18370,13.9543,"Animation, Comedy, Family, Fantasy",'Pixar',US,Brad Bird
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269,ROACH™,729501,A young pilot narrowly escapes the destruction...,2022-12-10,31,2000,0,"[CA, US]",en,0.000,0,0.5473,"Science Fiction, Animation",'schnüdlbug',CA,schnüdlbug
2270,Doomed: A Biological Cartoon!,438247,A fake documentary about the life and habits o...,2011-01-30,10,0,0,[US],en,0.000,0,0.0505,Animation,'El Señor Studio',ES,Guillermo García Carsí
2271,Distracted Blueberry,743540,Masculine tropes are undone to form a relation...,2019-10-24,273,0,0,[CA],fr,0.000,0,0.0256,Animation,,CA,Barry Doupé
2272,Animusic 3,737029,Animusic is a great electronic music experienc...,,0,223123,0,[US],en,0.000,0,0.0409,"Animation, Music, Family","'Animusic, LLC'",US,"David Crognale, Wayne Lytle"
2273,Outremer,719147,It's a story about a young boy who is afraid o...,2017-09-15,3,0,0,[US],en,0.000,0,0.1208,"Animation, Fantasy, Drama, Family","'Gobelins', ""L'école de l'image""",FR,"Hadrien Bonnet, Adrien Calle"

In [208]:
tmdb_movies_2d.release_date = pd.to_datetime(tmdb_movies_2d.release_date)

In [211]:
tmdb_movies_3d.release_date = pd.to_datetime(tmdb_movies_3d.release_date)

In [215]:
tmdb_movies_3d['release_year'] = tmdb_movies_3d.release_date.dt.year

In [216]:
tmdb_movies_2d['release_year'] = tmdb_movies_2d.release_date.dt.year

In [218]:
tmdb_movies_2d['release_month'] = tmdb_movies_2d.release_date.dt.month

In [219]:
tmdb_movies_3d['release_month'] = tmdb_movies_3d.release_date.dt.month

In [223]:
tmdb_movies_3d['release_weekday'] = tmdb_movies_3d.release_date.dt.strftime('%A')

In [224]:
tmdb_movies_2d['release_weekday'] = tmdb_movies_2d.release_date.dt.strftime('%A')

In [227]:
tmdb_movies_2d['release_weekday_num'] = tmdb_movies_2d.release_date.dt.weekday

In [228]:
tmdb_movies_3d['release_weekday_num'] = tmdb_movies_3d.release_date.dt.weekday

In [244]:
tmdb_movies_3d['origin_country'] = tmdb_movies_3d['origin_country'].astype(str).str[1:-1].str.replace('\'', '')

In [246]:
tmdb_movies_2d['origin_country'] = tmdb_movies_2d['origin_country'].astype(str).str[1:-1].str.replace('\'', '')

In [248]:
tmdb_movies_2d.to_csv('TMDB_2D_Movies.csv')

In [249]:
tmdb_movies_3d.to_csv('TMDB_3D_Movies.csv')

In [4]:
tmdb_movies_3d = pd.read_csv('TMDB_3D_Movies.csv')

In [8]:
tmdb_movies_3d.drop(columns=['Unnamed: 0'], inplace=True)

In [9]:
tmdb_movies_3d

,title,id,overview,release_date,runtime,budget,revenue,origin_country,original_language,vote_average,vote_count,popularity,genres_list,production_companies_list,production_countries_list,director,release_year,release_month,release_weekday,release_weekday_num
0,Spider-Man: Across the Spider-Verse,569094,"After reuniting with Gwen Stacy, Brooklyn’s fu...",2023-05-31,140,100000000,690897910,US,en,8.332,8484,28.9949,"Animation, Action, Adventure, Science Fiction","'Columbia Pictures', 'Sony Pictures Animation'...",US,"Kemp Powers, Justin K. Thompson, Joaquim Dos S...",2023.0,5.0,Wednesday,2.0
1,Spider-Man: Into the Spider-Verse,324857,Struggling to find his place in the world whil...,2018-12-06,117,90000000,394884133,US,en,8.393,17105,23.6672,"Animation, Action, Adventure, Science Fiction","'Columbia Pictures', 'Lord Miller', 'Pascal Pi...",US,"Bob Persichetti, Peter Ramsey, Rodney Rothman",2018.0,12.0,Thursday,3.0
2,The Wild Robot,1184918,"After a shipwreck, an intelligent robot called...",2024-09-12,102,78000000,331982078,US,en,8.305,5949,28.6254,"Family, Animation, Science Fiction, Adventure",'DreamWorks Animation',US,Chris Sanders,2024.0,9.0,Thursday,3.0
3,Flow,823219,"A solitary cat, displaced by a great flood, fi...",2024-08-29,85,3700000,17660107,LV,lv,8.084,2760,19.2123,"Animation, Adventure, Fantasy, Family","'Dream Well Studio', 'Sacrebleu Productions', ...","LV, BE, FR",Gints Zilbalodis,2024.0,8.0,Thursday,3.0
4,Ratatouille,2062,"Remy, a rat, possesses a palate far more refin...",2007-06-28,111,150000000,623726000,US,en,7.838,18370,13.9543,"Animation, Comedy, Family, Fantasy",'Pixar',US,Brad Bird,2007.0,6.0,Thursday,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269,ROACH™,729501,A young pilot narrowly escapes the destruction...,2022-12-10,31,2000,0,"CA, US",en,0.000,0,0.5473,"Science Fiction, Animation",'schnüdlbug',CA,schnüdlbug,2022.0,12.0,Saturday,5.0
2270,Doomed: A Biological Cartoon!,438247,A fake documentary about the life and habits o...,2011-01-30,10,0,0,US,en,0.000,0,0.0505,Animation,'El Señor Studio',ES,Guillermo García Carsí,2011.0,1.0,Sunday,6.0
2271,Distracted Blueberry,743540,Masculine tropes are undone to form a relation...,2019-10-24,273,0,0,CA,fr,0.000,0,0.0256,Animation,NaN,CA,Barry Doupé,2019.0,10.0,Thursday,3.0
2272,Animusic 3,737029,Animusic is a great electronic music experienc...,NaN,0,223123,0,US,en,0.000,0,0.0409,"Animation, Music, Family","'Animusic, LLC'",US,"David Crognale, Wayne Lytle",NaN,NaN,NaN,NaN
2273,Outremer,719147,It's a story about a young boy who is afraid o...,2017-09-15,3,0,0,US,en,0.000,0,0.1208,"Animation, Fantasy, Drama, Family","'Gobelins', ""L'école de l'image""",FR,"Hadrien Bonnet, Adrien Calle",2017.0,9.0,Friday,4.0

In [27]:
tmdb_movies_3d['genres_list'].str.split(',')

0       [Animation,  Action,  Adventure,  Science Fict...
1       [Animation,  Action,  Adventure,  Science Fict...
2       [Family,  Animation,  Science Fiction,  Advent...
3              [Animation,  Adventure,  Fantasy,  Family]
4                 [Animation,  Comedy,  Family,  Fantasy]
                              ...
2269                        [Science Fiction,  Animation]
2270                                          [Animation]
2271                                          [Animation]
2272                         [Animation,  Music,  Family]
2273               [Animation,  Fantasy,  Drama,  Family]
Name: genres_list, Length: 2274, dtype: object

In [22]:
genres = []
for g in tmdb_movies_3d['genres_list'].str.split(','):
    if type(g) is list:
        genres += g
    else:
        print(g)

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [29]:
genres = [g.strip() for g in genres]

In [32]:
pd.Series(genres).value_counts()

Animation          1852
Family              832
Comedy              730
Adventure           634
Fantasy             487
Science Fiction     432
Action              397
Drama               192
Horror              172
Music               104
Thriller             92
Documentary          74
TV Movie             57
Romance              51
Mystery              43
Crime                31
History              29
War                  27
Western               5
Name: count, dtype: int64

In [34]:
tmdb_movies_3d['release_weekday'].value_counts()

release_weekday
Friday       520
Thursday     460
Tuesday      346
Wednesday    303
Saturday     252
Monday       195
Sunday       144
Name: count, dtype: int64

In [35]:
countries = []
for c in tmdb_movies_3d['production_countries_list'].str.split(','):
    if type(c) is list:
        countries += c

In [37]:
countries = [c.strip() for c in countries]

In [41]:
country_counts_3d = pd.Series(countries).value_counts().reset_index()

In [45]:
country_counts_3d

   index  count
0     US   1138
1     FR    259
2     CA    164
3     JP    150
4     GB    136
..   ...    ...
65    GR      1
66    AL      1
67    SA      1
68    AF      1
69    PK      1

[70 rows x 2 columns]

In [42]:
country_codes=pd.read_csv('country_codes.csv')

In [48]:
country_counts_3d = pd.merge(country_counts_3d, country_codes, left_on='index', right_on='alpha-2', how='left')[['name', 'alpha-2', 'count']]

In [50]:
country_counts_3d.head(50)

                                                 name alpha-2  count
0                            United States of America      US   1138
1                                              France      FR    259
2                                              Canada      CA    164
3                                               Japan      JP    150
4   United Kingdom of Great Britain and Northern I...      GB    136
5                                               China      CN    117
6                                             Germany      DE     79
7                                               Spain      ES     52
8                                  Korea, Republic of      KR     40
9                                               India      IN     39
10                                            Belgium      BE     36
11                                          Australia      AU     29
12                                            Denmark      DK     28
13                                          Hong Kong      HK     24
14                                 Russian Federation      RU     24
15                                              Italy      IT     19
16                                             Brazil      BR     19
17                                           Malaysia      MY     18
18                        Netherlands, Kingdom of the      NL     16
19                                          Indonesia      ID     14
20                                            Finland      FI     14
21                                            Ireland      IE     14
22                                             Norway      NO     11
23                                          Argentina      AR      9
24                          Taiwan, Province of China      TW      8
25                                            Czechia      CZ      8
26                                           Thailand      TH      7
27                                             Mexico      MX      7
28                                       South Africa      ZA      7
29                                           Bulgaria      BG      7
30                                        Switzerland      CH      7
31                                             Latvia      LV      6
32                                         Luxembourg      LU      6
33                                             Poland      PL      6
34                                             Sweden      SE      5
35                                          Singapore      SG      5
36                                           Slovakia      SK      5
37                                        New Zealand      NZ      4
38                                             Israel      IL      3
39                                            Iceland      IS      3
40                                            Croatia      HR      3
41                                              Chile      CL      3
42                                              Qatar      QA      2
43                                                NaN     NaN      2
44                                 Dominican Republic      DO      2
45                               United Arab Emirates      AE      2
46                                            Nigeria      NG      2
47                                            Hungary      HU      2
48                                            Estonia      EE      2
49                                           Colombia      CO      2

In [53]:
tmdb_movies_3d['production_companies_list']

0       'Columbia Pictures', 'Sony Pictures Animation'...
1       'Columbia Pictures', 'Lord Miller', 'Pascal Pi...
2                                  'DreamWorks Animation'
3       'Dream Well Studio', 'Sacrebleu Productions', ...
4                                                 'Pixar'
                              ...
2269                                         'schnüdlbug'
2270                                    'El Señor Studio'
2271                                                  NaN
2272                                      'Animusic, LLC'
2273                     'Gobelins', "L'école de l'image"
Name: production_companies_list, Length: 2274, dtype: object

In [54]:
import shlex

In [59]:
import re

In [83]:
type(tmdb_movies_3d['production_companies_list'][0])

str

In [84]:
companies = []
for i, row in tmdb_movies_3d.iterrows():
    if type(row['production_companies_list']) is str:
        companies += re.findall(r"\'(.*?)\',?", row['production_companies_list'])

In [92]:
tmdb_movies_3d['profit'] = tmdb_movies_3d['revenue'] - tmdb_movies_3d['budget']

In [104]:
tmdb_movies_3d.genres_list.fillna(False, inplace=True)

In [115]:
tmdb_movies_3d_ani = tmdb_movies_3d[tmdb_movies_3d.genres_list.str.contains('Animation', na=False)]

In [118]:
tmdb_movies_3d_ani.reset_index(drop=True, inplace=True)

In [121]:
tmdb_movies_3d_ani.to_csv('TMDB_3D_Movies_Ani.csv')

In [19]:
cast_3d = []
crew_3d = []

In [7]:
cast = tmdb.Movies(129).credits()['cast']

In [13]:
[dict({'movie_id': 129}, **m) for m in cast]

[{'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 19587,
  'known_for_department': 'Acting',
  'name': 'Rumi Hiiragi',
  'original_name': '柊瑠美',
  'popularity': 1.8797,
  'profile_path': '/nTKM4GgfkrZvAOFL55uhEuckt7M.jpg',
  'cast_id': 3,
  'character': 'Chihiro (voice)',
  'credit_id': '52fe421bc3a36847f8004a97',
  'order': 0},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 19588,
  'known_for_department': 'Acting',
  'name': 'Miyu Irino',
  'original_name': '入野自由',
  'popularity': 2.7184,
  'profile_path': '/8qEEhHUObNvGQr4e6eqLu5z4qTz.jpg',
  'cast_id': 4,
  'character': 'Haku (voice)',
  'credit_id': '52fe421bc3a36847f8004a9b',
  'order': 1},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 19589,
  'known_for_department': 'Acting',
  'name': 'Mari Natsuki',
  'original_name': '夏木マリ',
  'popularity': 1.8964,
  'profile_path': '/MIFzUc77Sx57FQOZsoiGWEbpH2.jpg',
  'cast_id': 5,
  'character': 'Yubaba / Zeniba (voice)',
  'credit_id': '52fe421bc3a36847f8004a9f',
  'order': 2},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 19590,
  'known_for_department': 'Acting',
  'name': 'Takashi Naito',
  'original_name': '内藤剛志',
  'popularity': 1.6895,
  'profile_path': '/xwsm0ygjG79jLIogutwo6r64igy.jpg',
  'cast_id': 6,
  'character': 'Father (voice)',
  'credit_id': '52fe421bc3a36847f8004aa3',
  'order': 3},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 19591,
  'known_for_department': 'Acting',
  'name': 'Yasuko Sawaguchi',
  'original_name': '沢口靖子',
  'popularity': 1.7561,
  'profile_path': '/rWspusb13VeJowmctnniXYYTcqq.jpg',
  'cast_id': 7,
  'character': 'Mother (voice)',
  'credit_id': '52fe421bc3a36847f8004aa7',
  'order': 4},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 19592,
  'known_for_department': 'Acting',
  'name': 'Tatsuya Gashûin',
  'original_name': '我修院達也',
  'popularity': 1.5732,
  'profile_path': '/fLqIdkShknsJmZy4EfBWuWyHN4C.jpg',
  'cast_id': 8,
  'character': 'Aogaeru (voice)',
  'credit_id': '52fe421bc3a36847f8004aab',
  'order': 5},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 225730,
  'known_for_department': 'Acting',
  'name': 'Ryunosuke Kamiki',
  'original_name': '神木隆之介',
  'popularity': 2.4378,
  'profile_path': '/ut7ewXjdgUmgkhJ1EtbOo9tbc7s.jpg',
  'cast_id': 30,
  'character': 'Boh (voice)',
  'credit_id': '52fe421bc3a36847f8004b17',
  'order': 6},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 19594,
  'known_for_department': 'Acting',
  'name': 'Yumi Tamai',
  'original_name': '玉井夕海',
  'popularity': 0.6027,
  'profile_path': '/x9Td7e5F21cK9S1FCkobfqiJZ1c.jpg',
  'cast_id': 10,
  'character': 'Rin (voice)',
  'credit_id': '52fe421bc3a36847f8004aaf',
  'order': 7},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 40450,
  'known_for_department': 'Acting',
  'name': 'Yo Oizumi',
  'original_name': '大泉洋',
  'popularity': 1.8674,
  'profile_path': '/qw5KLuww2AEAk6JEssEkJY3wBn1.jpg',
  'cast_id': 25,
  'character': 'Bandai Frog (voice)',
  'credit_id': '52fe421bc3a36847f8004b07',
  'order': 8},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 554423,
  'known_for_department': 'Acting',
  'name': 'Koba Hayashi',
  'original_name': 'はやし・こば',
  'popularity': 0.3344,
  'profile_path': '/ceQ58tRgqMZ9gePHg8xkKarZm0M.jpg',
  'cast_id': 26,
  'character': 'River Spirit (voice)',
  'credit_id': '52fe421bc3a36847f8004b0b',
  'order': 9},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 20334,
  'known_for_department': 'Acting',
  'name': 'Tsunehiko Kamijô',
  'original_name': '上條恒彦',
  'popularity': 1.2841,
  'profile_path': '/v2poQi0qYEWdTaMf2pVTWmcdwZp.jpg',
  'cast_id': 27,
  'character': 'Chichiyaku (voice)',
  'credit_id': '52fe421bc3a36847f8004b0f',
  'order': 10},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 544088,
  'known_for_department': 'Acting',
  'name': 'Takehiko Ono',
  'original_name': '小野武彦',
  'popularity': 1.4311,
  'profile_path': '/8gcT8znk0l3YVZKvL7eVxYublTl.jpg',
  'cast_id': 28,
  'character': 'Aniyaku (voice)',
  'credit_id': '52fe421bc3a36847f8004b13',
  'order': 11},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 119243,
  'known_for_department': 'Acting',
  'name': 'Bunta Sugawara',
  'original_name': '菅原文太',
  'popularity': 2.0312,
  'profile_path': '/lHPLlP8zNwGMmcUI8rGks5vp8Vn.jpg',
  'cast_id': 31,
  'character': 'Kamaji (voice)',
  'credit_id': '52fe421bc3a36847f8004b1b',
  'order': 12},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 1530058,
  'known_for_department': 'Production',
  'name': 'Shigeru Wakita',
  'original_name': '脇田茂',
  'popularity': 0.2235,
  'profile_path': '/6iFm0U12QGmKDizbn08WqO1WXCU.jpg',
  'cast_id': 97,
  'character': '(voice)',
  'credit_id': '5fb05ded3a48c5003c7d7a18',
  'order': 13},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 1243817,
  'known_for_department': 'Acting',
  'name': 'Shirou Saitou',
  'original_name': '斎藤志郎',
  'popularity': 0.984,
  'profile_path': '/yJSrzULl9EuXI25E8REdIPY1Lkm.jpg',
  'cast_id': 98,
  'character': '(voice)',
  'credit_id': '5fb05df6c15f89003f838bc5',
  'order': 14},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 1608518,
  'known_for_department': 'Acting',
  'name': 'Michiko Yamamoto',
  'original_name': '山本道子',
  'popularity': 0.3935,
  'profile_path': '/cV4irDcmf4biTjTGaU1oPmFO7KR.jpg',
  'cast_id': 99,
  'character': '(voice)',
  'credit_id': '5fb05e02a22d3e004103aaf6',
  'order': 15},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2844828,
  'known_for_department': 'Acting',
  'name': 'Keiko Tsukamoto',
  'original_name': 'つかもと景子',
  'popularity': 0.4009,
  'profile_path': '/50AMEWXz2HUt3RFKoEuJk3Xl84k.jpg',
  'cast_id': 100,
  'character': '(voice)',
  'credit_id': '5fb05e0b5ed962003e107c9c',
  'order': 16},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 554612,
  'known_for_department': 'Acting',
  'name': 'Akio Nakamura',
  'original_name': '中村彰男',
  'popularity': 1.0632,
  'profile_path': '/z7GzSvEkb3vhA77FFS6JnkpEEbv.jpg',
  'cast_id': 101,
  'character': 'Kaonashi (voice)',
  'credit_id': '5fb05e14b54002003f597b15',
  'order': 17},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 2856717,
  'known_for_department': 'Acting',
  'name': 'Shinji Tokumaru',
  'original_name': '得丸伸二',
  'popularity': 0.1078,
  'profile_path': '/rYRs9Fbe5Cd0bJwxbM4bZp5MrKX.jpg',
  'cast_id': 102,
  'character': '(voice)',
  'credit_id': '5fb05e1f9ca75900404b384b',
  'order': 18},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 554367,
  'known_for_department': 'Acting',
  'name': 'Kaori Yamagata',
  'original_name': '山像かおり',
  'popularity': 0.7935,
  'profile_path': '/bhtFlZCoBxhq1FeNwx7ODNOZ73R.jpg',
  'cast_id': 103,
  'character': '(voice)',
  'credit_id': '5fb05e293a48c5003c7d7a9b',
  'order': 19},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2023580,
  'known_for_department': 'Acting',
  'name': 'Tsuzuki Kayako',
  'original_name': '都築香弥子',
  'popularity': 0.5684,
  'profile_path': '/9lKIm8V4yU3LztYj3B6LlOF9FyN.jpg',
  'cast_id': 104,
  'character': '(voice)',
  'credit_id': '5fb05e33d55e4d003cd049c2',
  'order': 20},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 2856718,
  'known_for_department': 'Acting',
  'name': 'Masahiro Asano',
  'original_name': '浅野雅博',
  'popularity': 0.1515,
  'profile_path': '/1FczbddfHUGlKg3z3opoV04pBZE.jpg',
  'cast_id': 105,
  'character': '(voice)',
  'credit_id': '5fb05e3cb54002004058bca5',
  'order': 21},
 {'movie_id': 129,
  'adult': False,
  'gender': 0,
  'id': 2856719,
  'known_for_department': 'Acting',
  'name': 'Kazutaka Hayashida',
  'original_name': 'Kazutaka Hayashida',
  'popularity': 0.0622,
  'profile_path': '/qxSLhaJLstgBm9DkWpD5AW4Va8A.jpg',
  'cast_id': 106,
  'character': '(voice)',
  'credit_id': '5fb05e45a22d3e004003380d',
  'order': 22},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856720,
  'known_for_department': 'Acting',
  'name': 'Ikuko Yamamoto',
  'original_name': '山本郁子',
  'popularity': 0.4505,
  'profile_path': '/ybMkOM1ztKz8vHH2SKlMb4RgkZ6.jpg',
  'cast_id': 107,
  'character': '(voice)',
  'credit_id': '5fb05e4e945c20003ee8575e',
  'order': 23},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856721,
  'known_for_department': 'Acting',
  'name': 'Mina Meguro',
  'original_name': '目黒未奈',
  'popularity': 0.2353,
  'profile_path': '/mx1n8cmUTMT0oZH4zyqo3zx84MN.jpg',
  'cast_id': 108,
  'character': '(voice)',
  'credit_id': '5fb05e5837b3a9003f015040',
  'order': 24},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 2856722,
  'known_for_department': 'Acting',
  'name': 'Tetsurô Ishibashi',
  'original_name': '石橋徹郎',
  'popularity': 0.1505,
  'profile_path': '/lMTfxLJEOSNFk0MgpA3RsoqxEdn.jpg',
  'cast_id': 109,
  'character': '(voice)',
  'credit_id': '5fb05e63d8f44e003ef7a213',
  'order': 25},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 2856723,
  'known_for_department': 'Acting',
  'name': 'Katsutomo Shîbara',
  'original_name': '椎原克知',
  'popularity': 0.2282,
  'profile_path': '/o8Wcta86QK2uHURyDqjTAxEajsj.jpg',
  'cast_id': 110,
  'character': '(voice)',
  'credit_id': '5fb05e75b6cff1003ac3a3cc',
  'order': 26},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856724,
  'known_for_department': 'Acting',
  'name': 'Shinobu Katabuchi',
  'original_name': '片渕忍',
  'popularity': 0.1516,
  'profile_path': '/gYMuEq00H2ESNnSNfGmBNSjld7T.jpg',
  'cast_id': 111,
  'character': '(voice)',
  'credit_id': '5fb05e88626208003eb39c17',
  'order': 27},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 1241949,
  'known_for_department': 'Acting',
  'name': 'Noriko Kitou',
  'original_name': '鬼頭典子',
  'popularity': 0.3203,
  'profile_path': '/hHtABHbBeTHA9ZGF2uX0zyWvS4H.jpg',
  'cast_id': 112,
  'character': '(voice)',
  'credit_id': '5fb05e91945c200041e92f35',
  'order': 28},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 2856725,
  'known_for_department': 'Acting',
  'name': 'Naoto Kaji',
  'original_name': '鍛治直人',
  'popularity': 0.2961,
  'profile_path': '/6fzuj6fYwrogkJ62sPAp5BMrFMw.jpg',
  'cast_id': 113,
  'character': '(voice)',
  'credit_id': '5fb05e9ad8f44e003ef7a28f',
  'order': 29},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 2856726,
  'known_for_department': 'Acting',
  'name': 'Yoshitaka Sukegawa',
  'original_name': 'Yoshitaka Sukegawa',
  'popularity': 0.0724,
  'profile_path': '/yahqVr8U7WPySJKULZQFC8qpkMp.jpg',
  'cast_id': 114,
  'character': '(voice)',
  'credit_id': '5fb05ea33a48c5003d7dd8a5',
  'order': 30},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856727,
  'known_for_department': 'Acting',
  'name': 'Aki Tachikawa',
  'original_name': '太刀川亞希',
  'popularity': 0.1716,
  'profile_path': '/yFuE7lgueXvBnrZno6yGgmx17oU.jpg',
  'cast_id': 115,
  'character': '(voice)',
  'credit_id': '5fb05eab3a48c5003f7de71f',
  'order': 31},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856728,
  'known_for_department': 'Acting',
  'name': 'Noriko Yamaya',
  'original_name': 'Noriko Yamaya',
  'popularity': 0.0741,
  'profile_path': '/2mX50DBmijvB5roubhchAECEawR.jpg',
  'cast_id': 116,
  'character': '(voice)',
  'credit_id': '5fb05ebcd8f44e003df6e673',
  'order': 32},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 2856729,
  'known_for_department': 'Acting',
  'name': 'Katsuhisa Matsuo',
  'original_name': '松尾勝久',
  'popularity': 0.0737,
  'profile_path': None,
  'cast_id': 117,
  'character': '(voice)',
  'credit_id': '5fb05ec5d55e4d003dcffb26',
  'order': 33},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 1921932,
  'known_for_department': 'Acting',
  'name': 'Masayuki Kizu',
  'original_name': '木津誠之',
  'popularity': 0.207,
  'profile_path': None,
  'cast_id': 118,
  'character': '(voice)',
  'credit_id': '5fb05ecfa22d3e003f04280f',
  'order': 34},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856730,
  'known_for_department': 'Acting',
  'name': 'Yôko Ôno',
  'original_name': '大野容子',
  'popularity': 0.1403,
  'profile_path': '/sn7LgwfIIi9dgAL3DQbSL5omivT.jpg',
  'cast_id': 119,
  'character': '(voice)',
  'credit_id': '5fb05ee7945c200040e8da0d',
  'order': 35},
 {'movie_id': 129,
  'adult': False,
  'gender': 0,
  'id': 2856731,
  'known_for_department': 'Acting',
  'name': 'Sachie Azuma',
  'original_name': 'Sachie Azuma',
  'popularity': 0.0962,
  'profile_path': None,
  'cast_id': 120,
  'character': '(voice)',
  'credit_id': '5fb05ef54a4bfc0041b4a98c',
  'order': 36},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 1039220,
  'known_for_department': 'Acting',
  'name': 'Ken Yasuda',
  'original_name': '安田顕',
  'popularity': 1.5515,
  'profile_path': '/mSEnXFHj8MnighBVG0yZdKOVyxI.jpg',
  'cast_id': 121,
  'character': 'Oshira-sama (voice)',
  'credit_id': '5fb05f00b6cff1003ac3a451',
  'order': 37},
 {'movie_id': 129,
  'adult': False,
  'gender': 2,
  'id': 1251804,
  'known_for_department': 'Acting',
  'name': 'Shigeyuki Totsugi',
  'original_name': '戸次重幸',
  'popularity': 1.0299,
  'profile_path': '/pK3B7H4qrzLy7nKr0lFKfqNRq91.jpg',
  'cast_id': 122,
  'character': 'Kashira (voice)',
  'credit_id': '5fb05f115ed962003d10f086',
  'order': 38},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2463593,
  'known_for_department': 'Acting',
  'name': 'Mayumi Saco',
  'original_name': '佐古真弓',
  'popularity': 0.5983,
  'profile_path': '/quaubRxGvU9IIaq2Nf7ejO3m5g2.jpg',
  'cast_id': 123,
  'character': '(voice)',
  'credit_id': '5fb05f1aec4552003ff6eb2a',
  'order': 39},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856733,
  'known_for_department': 'Acting',
  'name': 'Sonoko Soeda',
  'original_name': '添田園子',
  'popularity': 0.1185,
  'profile_path': '/xE6oVD5871XzK07zmQbEhqWpaaD.jpg',
  'cast_id': 124,
  'character': '(voice)',
  'credit_id': '5fb05f289ca75900404b3a2c',
  'order': 40},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856734,
  'known_for_department': 'Acting',
  'name': 'Akiko Tomihira',
  'original_name': 'Akiko Tomihira',
  'popularity': 0.1223,
  'profile_path': None,
  'cast_id': 125,
  'character': '(voice)',
  'credit_id': '5fb05f31945c200041e93017',
  'order': 41},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856735,
  'known_for_department': 'Acting',
  'name': 'Minako Masuda',
  'original_name': 'Minako Masuda',
  'popularity': 0.1649,
  'profile_path': None,
  'cast_id': 126,
  'character': '(voice)',
  'credit_id': '5fb05f3d6dc6c000422a6701',
  'order': 42},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856736,
  'known_for_department': 'Acting',
  'name': 'Orika Ono',
  'original_name': 'Orika Ono',
  'popularity': 0.1277,
  'profile_path': None,
  'cast_id': 127,
  'character': '(voice)',
  'credit_id': '5fb05f469ca759003f4a80ab',
  'order': 43},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856737,
  'known_for_department': 'Acting',
  'name': 'Rina Yamada',
  'original_name': '山田里奈',
  'popularity': 0.252,
  'profile_path': '/baVr49M1u7bcmEMD4NrP84aGzX0.jpg',
  'cast_id': 128,
  'character': '(voice)',
  'credit_id': '5fb05f4fdb154f003e49ed31',
  'order': 44},
 {'movie_id': 129,
  'adult': False,
  'gender': 0,
  'id': 2856738,
  'known_for_department': 'Acting',
  'name': 'Miwa Takachi',
  'original_name': 'Miwa Takachi',
  'popularity': 0.1044,
  'profile_path': None,
  'cast_id': 129,
  'character': '(voice)',
  'credit_id': '5fb05f583a48c5003c7d7b4d',
  'order': 45},
 {'movie_id': 129,
  'adult': False,
  'gender': 0,
  'id': 1887860,
  'known_for_department': 'Acting',
  'name': 'Hiromi Takeuchi',
  'original_name': 'Hiromi Takeuchi',
  'popularity': 0.0808,
  'profile_path': None,
  'cast_id': 130,
  'character': '(voice)',
  'credit_id': '5fb05f62626208003eb39d1d',
  'order': 46},
 {'movie_id': 129,
  'adult': False,
  'gender': 1,
  'id': 2856739,
  'known_for_department': 'Acting',
  'name': 'Makiko Oku',
  'original_name': '奥真紀子',
  'popularity': 0.2293,
  'profile_path': None,
  'cast_id': 131,
  'character': '(voice)',
  'credit_id': '5fb05f6a498ef9003f8104e4',
  'order': 47}]

In [16]:
tmdb_movies_3d_ani = pd.read_csv('TMDB_3D_Movies_Ani.csv')

In [17]:
tmdb_movies_3d_ani.head()

,Unnamed: 0,title,id,overview,release_date,runtime,budget,revenue,origin_country,original_language,...,popularity,genres_list,production_companies_list,production_countries_list,director,release_year,release_month,release_weekday,release_weekday_num,profit
0,0,Spider-Man: Across the Spider-Verse,569094,"After reuniting with Gwen Stacy, Brooklyn’s fu...",2023-05-31,140,100000000,690897910,US,en,...,28.9949,"Animation, Action, Adventure, Science Fiction","'Columbia Pictures', 'Sony Pictures Animation'...",US,"Kemp Powers, Justin K. Thompson, Joaquim Dos S...",2023.0,5.0,Wednesday,2.0,590897910
1,1,Spider-Man: Into the Spider-Verse,324857,Struggling to find his place in the world whil...,2018-12-06,117,90000000,394884133,US,en,...,23.6672,"Animation, Action, Adventure, Science Fiction","'Columbia Pictures', 'Lord Miller', 'Pascal Pi...",US,"Bob Persichetti, Peter Ramsey, Rodney Rothman",2018.0,12.0,Thursday,3.0,304884133
2,2,The Wild Robot,1184918,"After a shipwreck, an intelligent robot called...",2024-09-12,102,78000000,331982078,US,en,...,28.6254,"Family, Animation, Science Fiction, Adventure",'DreamWorks Animation',US,Chris Sanders,2024.0,9.0,Thursday,3.0,253982078
3,3,Flow,823219,"A solitary cat, displaced by a great flood, fi...",2024-08-29,85,3700000,17660107,LV,lv,...,19.2123,"Animation, Adventure, Fantasy, Family","'Dream Well Studio', 'Sacrebleu Productions', ...","LV, BE, FR",Gints Zilbalodis,2024.0,8.0,Thursday,3.0,13960107
4,4,Ratatouille,2062,"Remy, a rat, possesses a palate far more refin...",2007-06-28,111,150000000,623726000,US,en,...,13.9543,"Animation, Comedy, Family, Fantasy",'Pixar',US,Brad Bird,2007.0,6.0,Thursday,3.0,473726000

In [20]:
for i, row in tmdb_movies_3d_ani.iterrows():
    credits = tmdb.Movies(row['id']).credits()
    cast = [dict({'movie_id': row['id']}, **m) for m in credits['cast']]
    crew = [dict({'movie_id': row['id']}, **m) for m in credits['crew']]
    cast_3d += cast
    crew_3d += crew

In [24]:
cast_3d_df = pd.DataFrame(cast_3d)

In [25]:
crew_3d_df = pd.DataFrame(crew_3d)

In [28]:
cast_3d_df.drop(columns=['profile_path'], inplace=True)

In [30]:
crew_3d_df.drop(columns=['profile_path'], inplace=True)

In [31]:
cast_3d_df.to_csv('3D_Movies_Cast.csv', index=False)

In [32]:
crew_3d_df.to_csv('3D_Movies_Crew.csv', index=False)

In [35]:
tmdb_movies_3d_ani.drop(columns=['Unnamed: 0'], inplace=True)

In [19]:
tmdb_movies_3d_ani.to_csv('TMDB_3D_Movies_Ani.csv', index=False)

NameError: name 'tmdb_movies_3d_ani' is not defined

In [4]:
tmdb_movies_2d = pd.read_csv('TMDB_2D_Movies.csv')

In [9]:
for i, row in tmdb_movies_2d.iterrows():
    try:
        tmdb_2d.append(tmdb.Movies(row['id']).info())
    except:
        continue

In [18]:
pd.merge(tmdb_movies_2d, pd.DataFrame(tmdb_2d)['adult'], left_index=True, right_index=True).to_csv('TMDB_2D_Movies.csv', index=False)

In [24]:
tmdb_movies_3d = pd.read_csv('TMDB_3D_Movies_Ani.csv')

In [25]:
tmdb_3d = []

In [ ]:
for i, row in tmdb_movies_3d.iterrows():
    try:
        tmdb_3d.append(tmdb.Movies(row['id']).info())
    except:
        continue

In [ ]:
pd.DataFrame(tmdb_3d)

In [ ]:
pd.merge(tmdb_movies_3d, pd.DataFrame(tmdb_3d)['adult'], left_index=True, right_index=True)

In [15]:
tmdb_movies_2d.drop(columns=['Unnamed: 0'], inplace=True)

In [40]:
tmdb_movies_2d.to_csv('TMDB_2D_Movies.csv', index=False)

In [16]:
tmdb_movies_2d.head()

,title,id,overview,release_date,runtime,budget,revenue,origin_country,original_language,vote_average,...,genres_list,production_companies_list,production_countries_list,director,release_year,release_month,release_weekday,release_weekday_num,profit,bayesian_rating
0,Spirited Away,129,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,125,19000000,274925095,JP,ja,8.500,...,"Animation, Family, Fantasy","'Studio Ghibli', 'Tokuma Shoten', 'Nippon Tele...",JP,Hayao Miyazaki,2001.0,7.0,Friday,4.0,255925095,8.322954
1,Attack on Titan: THE LAST ATTACK,1333100,A colossal-sized omnibus film bringing togethe...,2024-03-20,145,0,21525687,JP,ja,8.736,...,"Animation, Action, Adventure, Drama","'MAPPA', 'Pony Canyon'",JP,Yuichiro Hayashi,2024.0,3.0,Wednesday,2.0,21525687,6.044342
2,Grave of the Fireflies,12477,"In the final months of World War II, 14-year-o...",1988-04-16,89,3700000,842132,JP,ja,8.400,...,"Animation, Drama, War",'Studio Ghibli',JP,Isao Takahata,1988.0,4.0,Saturday,5.0,-2857868,6.805540
3,Violet Evergarden: The Movie,533514,As the world moves on from the war and technol...,2020-09-18,140,0,20339624,JP,ja,8.287,...,"Animation, Drama, Fantasy, Romance","'Kyoto Animation', 'ABC Animation', 'Pony Cany...",JP,Taichi Ishidate,2020.0,9.0,Friday,4.0,20339624,6.076824
4,Look Back,1244492,"Popular, outgoing Fujino is celebrated by her ...",2024-06-28,58,0,12648664,JP,ja,8.000,...,"Animation, Drama","'Studio Durian', 'avex pictures', 'Shueisha'",JP,Kiyotaka Oshiyama,2024.0,6.0,Friday,4.0,12648664,6.071912

In [9]:
tmdb_movies_3d = pd.read_csv('TMDB_3D_Movies_Ani.csv')
cast_3d = []

In [10]:
for i, row in tmdb_movies_3d.iterrows():
    credits = tmdb.Movies(row['id']).credits()
    cast = [dict({'movie_id': row['id']}, **m) for m in credits['cast']]
    cast_3d += cast

In [11]:
cast_3d_df = pd.DataFrame(cast_3d)

In [12]:
cast_3d_df.drop(columns=['profile_path'], inplace=True)

In [13]:
cast_3d_df.to_csv('3D_Movies_Cast.csv', index=False)